# Site settings
title: Shawn Coots
email: shawncoots@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a web designer/writer/illustrator living and working in Louisville, Kentucky. I have an beautiful wife and three silly cats.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shawncoots
github_username:  shawncoots

# Build settings
markdown: kramdown
