# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Shawn Coots Writes Stories
tagline:             ''
description:         'I am a designer and writer living and working in Louisville, Kentucky. I have an amazing wife and three beautiful cats. We watch a lot of Netflix.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
